name: tabu
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  circular_countdown_timer: ^0.2.3
  auto_size_text: ^3.0.0
  auto_route: ^5.0.4
  auto_route_generator: ^5.0.3
  slide_countdown: ^0.4.1
  flutter_timer_countdown: ^1.0.5
  provider: ^6.0.5
  google_fonts: ^4.0.3
  material_dialogs: ^1.1.4
  toast: ^0.3.0
  equatable: ^2.0.5
  flutter_screenutil: ^5.7.0
  bloc: ^8.1.1
  get_it: ^7.2.0
  flutter_bloc: ^8.1.2
  dartz: ^0.10.1
  store_redirect: ^2.0.1
  google_mobile_ads: ^2.4.0
  assets_audio_player: ^3.0.6
  flutter_animated_button: ^2.0.3
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mobx_codegen: ^2.1.1
  build_runner: ^2.3.3
  change_app_package_name: ^1.1.0
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/audios/
