class DummyData {
  static List<Map<String, dynamic>> getAllData() {
    return [
      {
        "id": 0,
        "word": 'FİİL',
        "tabu1": 'İş',
        "tabu2": 'Oluş',
        "tabu3": 'Hareket',
        "tabu4": 'Eylem',
        "tabu5": 'Sözcük',
      },
      {
        "id": 1,
        "word": 'OKKA',
        "tabu1": 'Ağırlık',
        "tabu2": 'Ölçü',
        "tabu3": 'Birim',
        "tabu4": 'Kilo',
        "tabu5": 'Tartı',
      },
      {
        "id": 2,
        "word": 'ÖYKÜ',
        "tabu1": 'Hikâye',
        "tabu2": 'Kahraman',
        "tabu3": 'Yazar',
        "tabu4": 'Yer',
        "tabu5": 'Kitap',
      },
      {
        "id": 3,
        "word": 'ÖNERİ',
        "tabu1": 'Teklif',
        "tabu2": 'Çözüm',
        "tabu3": 'Yol',
        "tabu4": 'Cümle',
        "tabu5": 'İyi Olur',
      },
      {
        "id": 4,
        "word": 'MECAZ',
        "tabu1": 'Kelime',
        "tabu2": 'Sözcük',
        "tabu3": 'Gerçek Anlam',
        "tabu4": 'Yarı Anlam',
        "tabu5": 'Terim Anlam',
      },
      {
        "id": 5,
        "word": 'VARSAYIM',
        "tabu1": 'Olmamış',
        "tabu2": 'Tut ki',
        "tabu3": 'Farz et',
        "tabu4": 'Diyelim',
        "tabu5": 'Cümle',
      },
      {
        "id": 6,
        "word": 'ABARTMA',
        "tabu1": 'Mübalağa',
        "tabu2": 'Farklı',
        "tabu3": 'Aşırı',
        "tabu4": 'Göstermek',
        "tabu5": 'Olduğundan',
      },
      {
        "id": 7,
        "word": 'ÖDEV',
        "tabu1": 'Ders',
        "tabu2": 'Çalışmak',
        "tabu3": 'Okul',
        "tabu4": 'Öğretmen',
        "tabu5": 'Ev',
      },
      {
        "id": 8,
        "word": 'AVİZE',
        "tabu1": 'Kristal',
        "tabu2": 'Tavan',
        "tabu3": 'Işık',
        "tabu4": 'Aydınlık',
        "tabu5": 'Lamba',
      },
      {
        "id": 9,
        "word": 'KOORDİNAT',
        "tabu1": 'Enlem',
        "tabu2": 'Boylam',
        "tabu3": 'Belirtmek',
        "tabu4": 'Vermek',
        "tabu5": 'Yer',
      },
      {
        "id": 10,
        "word": 'HARABE',
        "tabu1": 'Yıkık',
        "tabu2": 'Eski',
        "tabu3": 'Tarihi',
        "tabu4": 'Efes',
        "tabu5": 'Gezmek',
      },
      {
        "id": 11,
        "word": 'ŞAMDAN',
        "tabu1": 'Mum',
        "tabu2": 'Işık',
        "tabu3": 'Aydınlık',
        "tabu4": 'Yakmak',
        "tabu5": 'Süs',
      },
      {
        "id": 12,
        "word": 'TIRABZAN',
        "tabu1": 'Merdiven',
        "tabu2": 'Korkuluk',
        "tabu3": 'İnmek',
        "tabu4": 'Çıkmak',
        "tabu5": 'Bina',
      },
      {
        "id": 13,
        "word": 'ANTİKA',
        "tabu1": 'Müzayede',
        "tabu2": 'Zengin',
        "tabu3": 'Eski',
        "tabu4": 'Tarihi',
        "tabu5": 'Tablo',
      },
      {
        "id": 14,
        "word": 'SAĞDIÇ',
        "tabu1": 'Düğün',
        "tabu2": 'Gelin',
        "tabu3": 'Güvey',
        "tabu4": 'Sırtına Vurmak',
        "tabu5": 'Damat',
      },
      {
        "id": 15,
        "word": 'SATRANÇ',
        "tabu1": 'Şah-Mat',
        "tabu2": 'Kale',
        "tabu3": 'Vezir',
        "tabu4": 'Piyon',
        "tabu5": 'Fil',
      },
      {
        "id": 16,
        "word": 'PİŞMANLIK',
        "tabu1": 'Hata',
        "tabu2": 'Yanlış',
        "tabu3": 'Keşke',
        "tabu4": 'Son',
        "tabu5": 'Üzülmek',
      },
      {
        "id": 17,
        "word": 'DUY',
        "tabu1": 'İşitmek',
        "tabu2": 'Tavan',
        "tabu3": 'Işık',
        "tabu4": 'İşitmek',
        "tabu5": 'Anahtar',
      },
      {
        "id": 18,
        "word": 'ADEM ELMASI',
        "tabu1": 'Gırtlak',
        "tabu2": 'Çıkıntı',
        "tabu3": 'Boğaz',
        "tabu4": 'Erkek',
        "tabu5": 'Yutak',
      },
      {
        "id": 19,
        "word": 'MANGALA',
        "tabu1": 'Oyun',
        "tabu2": 'Çukur',
        "tabu3": 'Taş',
        "tabu4": 'Eski',
        "tabu5": 'OSmanlı',
      },
      {
        "id": 20,
        "word": 'MALA',
        "tabu1": 'Usta',
        "tabu2": 'İnşaat',
        "tabu3": 'Sıva',
        "tabu4": 'Çimento',
        "tabu5": 'Duvar',
      },
      {
        "id": 21,
        "word": 'TİYATRO',
        "tabu1": 'Sahne',
        "tabu2": 'Roma',
        "tabu3": 'Oyum',
        "tabu4": 'Skeç',
        "tabu5": 'Güldür',
      },
      {
        "id": 22,
        "word": 'BAĞLAMA',
        "tabu1": 'Saz',
        "tabu2": 'Tel',
        "tabu3": 'Akort',
        "tabu4": 'Türkü',
        "tabu5": 'Müzik',
      },
      {
        "id": 23,
        "word": 'DOST',
        "tabu1": 'Samimi',
        "tabu2": 'Dürüst',
        "tabu3": 'Arkadaş',
        "tabu4": 'Ahlaklı',
        "tabu5": 'Güven',
      },
      {
        "id": 24,
        "word": 'KEDİ',
        "tabu1": 'Pati',
        "tabu2": 'Fare',
        "tabu3": 'Kuyruk',
        "tabu4": 'Hayvan',
        "tabu5": 'Tüy',
      },
      {
        "id": 25,
        "word": 'EMPATİ',
        "tabu1": 'Başkası',
        "tabu2": 'Kendini',
        "tabu3": 'Yerine',
        "tabu4": 'Düşünme',
        "tabu5": 'Koyma',
      },
      {
        "id": 26,
        "word": 'HOŞGÖRÜ',
        "tabu1": 'Anlayış',
        "tabu2": 'Empati',
        "tabu3": 'Ne olursan',
        "tabu4": 'Gel',
        "tabu5": 'Mevlana',
      },
      {
        "id": 27,
        "word": 'ULEMA',
        "tabu1": 'Osmanlı',
        "tabu2": 'Alim',
        "tabu3": 'Hoca',
        "tabu4": 'Din',
        "tabu5": 'Bilgin',
      },
      {
        "id": 28,
        "word": 'Futbol',
        "tabu1": 'Top',
        "tabu2": 'Ayak',
        "tabu3": 'Kale',
        "tabu4": 'Kaleci',
        "tabu5": 'Forma',
      },
      {
        "id": 29,
        "word": 'FİDAN',
        "tabu1": 'Ağaç',
        "tabu2": 'Büyümek',
        "tabu3": 'Küçük',
        "tabu4": 'Orman',
        "tabu5": 'Dikmek',
      },
      {
        "id": 30,
        "word": 'ÇIRA',
        "tabu1": 'Ateş',
        "tabu2": 'Mangal',
        "tabu3": 'Odun',
        "tabu4": 'Tahta',
        "tabu5": 'Kolay',
      },
      {
        "id": 31,
        "word": 'ADİDAS',
        "tabu1": 'Ayakkabı',
        "tabu2": 'Spor',
        "tabu3": 'Marka',
        "tabu4": 'Eşofman',
        "tabu5": 'Sponsor',
      },
      {
        "id": 32,
        "word": 'PRATİK',
        "tabu1": 'Kolay',
        "tabu2": 'Hızlı',
        "tabu3": 'Zeka',
        "tabu4": 'Çabuk',
        "tabu5": 'Çözüm',
      },
      {
        "id": 33,
        "word": 'TEMBEL',
        "tabu1": 'Miskin',
        "tabu2": 'Uyuşuk',
        "tabu3": 'Yavaş',
        "tabu4": 'Ağır',
        "tabu5": 'Kedi',
      },
      {
        "id": 34,
        "word": 'MESAİ',
        "tabu1": 'Falza',
        "tabu2": 'İş',
        "tabu3": 'Kalmak',
        "tabu4": 'Ekstra',
        "tabu5": 'Akşam',
      },
      {
        "id": 35,
        "word": 'KANEPE',
        "tabu1": 'Oturmak',
        "tabu2": 'Koltuk',
        "tabu3": 'Salon',
        "tabu4": 'Televizyon',
        "tabu5": 'Misafir',
      },
      {
        "id": 36,
        "word": 'SOĞAN',
        "tabu1": 'Kokmak',
        "tabu2": 'Göz Yaşarması',
        "tabu3": 'Yemek',
        "tabu4": 'Sarımsak',
        "tabu5": 'Misafir',
      },
      {
        "id": 37,
        "word": 'FLAMA',
        "tabu1": 'Bayrak',
        "tabu2": 'Tören',
        "tabu3": 'Ay Yıldız',
        "tabu4": 'Okul',
        "tabu5": 'Asmak',
      },
      {
        "id": 38,
        "word": 'MÜSVEDDE',
        "tabu1": 'Yazmak',
        "tabu2": 'Karalamak',
        "tabu3": 'Kağıt',
        "tabu4": 'Not Almak',
        "tabu5": 'Sınav',
      },
      {
        "id": 39,
        "word": 'SİFTAH',
        "tabu1": 'İlk',
        "tabu2": 'Esnaf',
        "tabu3": 'Kazanç',
        "tabu4": 'Satmak',
        "tabu5": 'Gün',
      },
      {
        "id": 40,
        "word": 'BUĞU',
        "tabu1": 'Buhar',
        "tabu2": 'Soğuk',
        "tabu3": 'Sıcak',
        "tabu4": 'Araba',
        "tabu5": 'Cam',
      },
      {
        "id": 41,
        "word": 'BUĞU',
        "tabu1": 'Buhar',
        "tabu2": 'Soğuk',
        "tabu3": 'Sıcak',
        "tabu4": 'Araba',
        "tabu5": 'Cam',
      },
      {
        "id": 42,
        "word": 'ELON MUSK',
        "tabu1": 'Tesla',
        "tabu2": 'Space-X',
        "tabu3": 'Zengin',
        "tabu4": 'Yazılımcı',
        "tabu5": 'Dünya',
      },
      {
        "id": 43,
        "word": 'NUMUNE',
        "tabu1": 'Örnek',
        "tabu2": 'Tahlil',
        "tabu3": 'Küçük',
        "tabu4": 'Test Etmek',
        "tabu5": 'Parça',
      },
      {
        "id": 44,
        "word": 'AKSİ',
        "tabu1": 'Sinirli',
        "tabu2": 'Kızgın',
        "tabu3": 'Zıt',
        "tabu4": 'Ters',
        "tabu5": 'Asabi',
      },
      {
        "id": 45,
        "word": 'FALCI',
        "tabu1": 'Geleck',
        "tabu2": 'Tahmin',
        "tabu3": 'Kahve',
        "tabu4": 'Yorum',
        "tabu5": 'Uydurmak',
      },
      {
        "id": 46,
        "word": 'HAYVANAT BAHÇESİ',
        "tabu1": 'Kafes',
        "tabu2": 'Darıca',
        "tabu3": 'Aslan',
        "tabu4": 'Bakıcı',
        "tabu5": 'Ziyaret',
      },
      {
        "id": 47,
        "word": 'CELAL ŞENGÖR',
        "tabu1": 'Jeofizik',
        "tabu2": 'İlber Ortaylı',
        "tabu3": 'Bilim',
        "tabu4": 'Profesör',
        "tabu5": 'Şişman',
      },
      {
        "id": 48,
        "word": 'İLBER ORTAYLI',
        "tabu1": 'Fatih Altaylı',
        "tabu2": 'Celal Şengör',
        "tabu3": 'Tarihçi',
        "tabu4": 'Profesör',
        "tabu5": 'Cahil',
      },
      {
        "id": 49,
        "word": 'ALZHEİMER',
        "tabu1": 'Unutkanlık',
        "tabu2": 'Hastalık',
        "tabu3": 'Yaşlı',
        "tabu4": 'Hatırlamak',
        "tabu5": 'B12',
      },
      {
        "id": 50,
        "word": 'FAY',
        "tabu1": 'Hat',
        "tabu2": 'Deprem',
        "tabu3": 'Kırılmak',
        "tabu4": 'İstanbul',
        "tabu5": '1999',
      },
      {
        "id": 51,
        "word": 'GÖKKUŞAĞI',
        "tabu1": 'Renkli',
        "tabu2": 'Hava',
        "tabu3": 'Yağmur',
        "tabu4": 'Güneş',
        "tabu5": 'Yarım Daire',
      },
      {
        "id": 52,
        "word": 'İKİLEM',
        "tabu1": 'Karasız',
        "tabu2": 'Durum',
        "tabu3": 'Acaba',
        "tabu4": 'Tercih',
        "tabu5": 'Arada Kalmak',
      },
      {
        "id": 53,
        "word": 'HAYIFLANMAK',
        "tabu1": 'Pişmanlık',
        "tabu2": 'Üzüntü',
        "tabu3": 'Geçmiş',
        "tabu4": 'Ders Almak',
        "tabu5": 'Keşke',
      },
      {
        "id": 54,
        "word": 'OLASILIK',
        "tabu1": 'İhtimal',
        "tabu2": 'Belki',
        "tabu3": 'Olabilir',
        "tabu4": 'Bakarız',
        "tabu5": 'Anlam',
      },
      {
        "id": 55,
        "word": 'İFTAR',
        "tabu1": 'Oruç',
        "tabu2": 'Ramazan',
        "tabu3": '11 Ay',
        "tabu4": 'Ezan',
        "tabu5": 'Aç Kalmak',
      },
      {
        "id": 56,
        "word": 'MANİDAR',
        "tabu1": 'Anlamlı',
        "tabu2": 'Özel',
        "tabu3": 'Anlam',
        "tabu4": 'Düşündürücü',
        "tabu5": 'İmalı',
      },
      {
        "id": 57,
        "word": 'ÇIRAK',
        "tabu1": 'Usta',
        "tabu2": 'Acemi',
        "tabu3": 'Zanaat',
        "tabu4": 'Amele',
        "tabu5": 'Ayak İşleri',
      },
      {
        "id": 58,
        "word": 'SPESİFİK',
        "tabu1": 'Belirgin',
        "tabu2": 'Özgün',
        "tabu3": 'Özgül',
        "tabu4": 'Has',
        "tabu5": 'Özel',
      },
      {
        "id": 59,
        "word": 'KOLEJ',
        "tabu1": 'Okul',
        "tabu2": 'Ücretli',
        "tabu3": 'Zengin',
        "tabu4": 'Lüks',
        "tabu5": 'Özel',
      },
      {
        "id": 60,
        "word": 'SIRITMAK',
        "tabu1": 'Gülmek',
        "tabu2": 'Mutlu Olmak',
        "tabu3": 'Belirgin',
        "tabu4": 'Ortaya Çıkmak',
        "tabu5": 'Dikkat',
      },
      {
        "id": 61,
        "word": 'YOUTUBE',
        "tabu1": 'V"id"eo',
        "tabu2": 'Kanal',
        "tabu3": 'İzlenme',
        "tabu4": 'İnternet',
        "tabu5": 'Beğeni',
      },
      {
        "id": 62,
        "word": 'BASKETBOL',
        "tabu1": 'Pota',
        "tabu2": 'Saha',
        "tabu3": 'Gard',
        "tabu4": 'Top',
        "tabu5": 'File',
      },
      {
        "id": 63,
        "word": 'SEKSEK',
        "tabu1": 'Kutu',
        "tabu2": 'Taş',
        "tabu3": 'İlkokul',
        "tabu4": 'Ayak',
        "tabu5": 'Atmak',
      },
      {
        "id": 64,
        "word": 'RİTİM',
        "tabu1": 'Müzik',
        "tabu2": 'Tempo',
        "tabu3": 'Tasarım',
        "tabu4": 'Konu',
        "tabu5": 'Resim',
      },
      {
        "id": 65,
        "word": 'GRAFİK',
        "tabu1": 'Görsel',
        "tabu2": 'Tasarım',
        "tabu3": 'Bilgisayar',
        "tabu4": 'Çizim',
        "tabu5": 'Konu',
      },
      {
        "id": 66,
        "word": 'TABURE',
        "tabu1": 'Oturmak',
        "tabu2": 'Sandalye',
        "tabu3": 'Koltuk',
        "tabu4": 'Yemekhane',
        "tabu5": 'Sırt',
      },
      {
        "id": 67,
        "word": 'RADİKAL',
        "tabu1": 'Kesin',
        "tabu2": 'Kökten',
        "tabu3": 'Tamamen',
        "tabu4": 'Aşırı',
        "tabu5": 'Denenmemiş',
      },
      {
        "id": 68,
        "word": 'ADOLF HİTLER',
        "tabu1": 'Bıyık',
        "tabu2": 'Almanya',
        "tabu3": 'Yahudi',
        "tabu4": 'Yakmak',
        "tabu5": 'Kazan',
      },
      {
        "id": 69,
        "word": 'YAZILIM',
        "tabu1": 'Teknoloji',
        "tabu2": 'Bilgisayar',
        "tabu3": 'Kod',
        "tabu4": 'Robot',
        "tabu5": 'Oyun',
      },
      {
        "id": 70,
        "word": 'TELEVİZYON',
        "tabu1": 'İzlemek',
        "tabu2": 'Seyretmek',
        "tabu3": 'Salon',
        "tabu4": 'Antem',
        "tabu5": 'Kumanda',
      },
      {
        "id": 71,
        "word": 'Çikolata',
        "tabu1": 'Süt',
        "tabu2": 'Kakao',
        "tabu3": 'Bitter',
        "tabu4": 'Kahverengi',
        "tabu5": 'Eti',
      },
      {
        "id": 72,
        "word": 'Cüzdan',
        "tabu1": 'Para',
        "tabu2": 'Kart',
        "tabu3": 'Cartvizit',
        "tabu4": 'Kimlik',
        "tabu5": 'Nakit',
      },
      {
        "id": 73,
        "word": 'Parfüm',
        "tabu1": 'Koku',
        "tabu2": 'Sıkmak',
        "tabu3": 'Güzel',
        "tabu4": 'Kadın',
        "tabu5": 'Ferah',
      },
      {
        "id": 74,
        "word": 'PlatStation',
        "tabu1": 'Kol',
        "tabu2": 'Oyun',
        "tabu3": 'Konsol',
        "tabu4": 'Sonny',
        "tabu5": 'Futbol',
      },
      {
        "id": 75,
        "word": 'Monitör',
        "tabu1": 'Ekran',
        "tabu2": 'Görüntü',
        "tabu3": 'İnç',
        "tabu4": 'Çözünürlük',
        "tabu5": 'Bilgisayar',
      },
      {
        "id": 76,
        "word": 'Kulaklık',
        "tabu1": 'Ses',
        "tabu2": 'Kulak',
        "tabu3": 'Mikrofon',
        "tabu4": 'Telefon',
        "tabu5": 'Kablo',
      },
      {
        "id": 77,
        "word": 'Dumbell',
        "tabu1": 'Ağırlık',
        "tabu2": 'Spor',
        "tabu3": 'Kas',
        "tabu4": 'Fitness',
        "tabu5": 'Kilo',
      },
      {
        "id": 78,
        "word": 'Klavye Delikanlısı',
        "tabu1": 'Bilgisayar',
        "tabu2": 'Yazmak',
        "tabu3": 'Söylemek',
        "tabu4": 'Hakaret',
        "tabu5": 'Yorum',
      },
      {
        "id": 79,
        "word": 'Halısaha',
        "tabu1": 'Futbol',
        "tabu2": 'Erkek',
        "tabu3": 'Maç',
        "tabu4": 'Forma',
        "tabu5": 'Gol',
      },
      {
        "id": 80,
        "word": 'Yatak',
        "tabu1": 'Yastık',
        "tabu2": 'Yorgam',
        "tabu3": 'Battaniye',
        "tabu4": 'Uyumak',
        "tabu5": 'Kalkmak',
      },
      {
        "id": 81,
        "word": 'Hayal Etmek',
        "tabu1": 'Düşünmek',
        "tabu2": 'Göz',
        "tabu3": 'Rüya',
        "tabu4": 'Hedef',
        "tabu5": 'Düş',
      },
      {
        "id": 82,
        "word": 'Eyfel Kulesi',
        "tabu1": 'Adolf Hitler',
        "tabu2": 'Fransa',
        "tabu3": 'Paris',
        "tabu4": 'Uzun',
        "tabu5": 'Orta',
      },
      {
        "id": 83,
        "word": 'Yazılımcı',
        "tabu1": 'Kod',
        "tabu2": 'Yazmak',
        "tabu3": 'Şapka',
        "tabu4": 'Bilgisayar',
        "tabu5": 'Uygulama',
      },
      {
        "id": 84,
        "word": 'TOGG',
        "tabu1": 'Otomobil',
        "tabu2": 'Yerli',
        "tabu3": 'Araba',
        "tabu4": 'Milli',
        "tabu5": 'Bursa',
      },
      {
        "id": 85,
        "word": 'Vapur',
        "tabu1": 'Deniz',
        "tabu2": 'Gemi',
        "tabu3": 'Araba',
        "tabu4": 'İskele',
        "tabu5": 'Binmek',
      },
      {
        "id": 86,
        "word": 'Tekne',
        "tabu1": 'Deniz',
        "tabu2": 'Gemi',
        "tabu3": 'Tur',
        "tabu4": 'İskele',
        "tabu5": 'Gezmek',
      },
      {
        "id": 87,
        "word": 'Sokrates',
        "tabu1": 'Savunma',
        "tabu2": 'Felsefe',
        "tabu3": 'Yunan',
        "tabu4": 'Düşünür',
        "tabu5": 'Mitoloji',
      },
      {
        "id": 88,
        "word": 'kapitülasyon',
        "tabu1": 'Yabancı',
        "tabu2": 'Zarak',
        "tabu3": 'Yarar',
        "tabu4": 'Yurttaş',
        "tabu5": 'Ayrıcalık',
      },
      {
        "id": 89,
        "word": 'kapitülasyon',
        "tabu1": 'Yabancı',
        "tabu2": 'Zarak',
        "tabu3": 'Yarar',
        "tabu4": 'Yurttaş',
        "tabu5": 'Ayrıcalık',
      },
      {
        "id": 90,
        "word": 'Gardırop',
        "tabu1": 'Kıyafet',
        "tabu2": 'Giyinmel',
        "tabu3": 'Asmak',
        "tabu4": 'Yerleştirmek',
        "tabu5": 'Ayna',
      },
      {
        "id": 91,
        "word": 'Kilim',
        "tabu1": 'Halı',
        "tabu2": 'Sermek',
        "tabu3": 'Yer',
        "tabu4": 'Basmak',
        "tabu5": 'Overlok',
      },
      {
        "id": 92,
        "word": 'Gergedan',
        "tabu1": 'Boynuz',
        "tabu2": 'Çin',
        "tabu3": 'Kesmek',
        "tabu4": 'Öldürmek',
        "tabu5": 'Adrika',
      },
      {
        "id": 93,
        "word": 'komünizm',
        "tabu1": 'Özel',
        "tabu2": 'Mülkiyet',
        "tabu3": 'Üreitim',
        "tabu4": 'Ortak',
        "tabu5": 'Eşit',
      },
      {
        "id": 94,
        "word": 'Faşizm',
        "tabu1": 'Baskıcı',
        "tabu2": 'Radikal',
        "tabu3": 'Otoriter',
        "tabu4": 'İtalya',
        "tabu5": '"id"eoloji',
      },
      {
        "id": 95,
        "word": 'Kapitalizm',
        "tabu1": 'Özel',
        "tabu2": 'Mülkiyet',
        "tabu3": 'Kar',
        "tabu4": 'Tüketim',
        "tabu5": 'Serbest',
      },
      {
        "id": 96,
        "word": 'Traktör',
        "tabu1": 'Çifçi',
        "tabu2": 'Tarım',
        "tabu3": 'Yetiştirmek',
        "tabu4": 'Hayvan',
        "tabu5": 'Tarla',
      },
      {
        "id": 97,
        "word": 'Sömürgecilik',
        "tabu1": 'Almak',
        "tabu2": 'Sınır',
        "tabu3": 'Ülke',
        "tabu4": 'Siyasal',
        "tabu5": 'Özgürlük',
      },
      {
        "id": 98,
        "word": 'Para',
        "tabu1": 'L"id"ya',
        "tabu2": 'Almak',
        "tabu3": 'Maaş',
        "tabu4": 'Değer',
        "tabu5": 'Vermek',
      },
      {
        "id": 99,
        "word": 'Serbest Piyasa',
        "tabu1": 'Alıcı',
        "tabu2": 'Satıcı',
        "tabu3": 'Arz',
        "tabu4": 'Belirlemek',
        "tabu5": 'Talep',
      },
      {
        "id": 100,
        "word": 'Radyo',
        "tabu1": 'Anten',
        "tabu2": 'Ses',
        "tabu3": 'Eski',
        "tabu4": 'Frekans',
        "tabu5": 'Talep',
      },
      {
        "id": 101,
        "word": 'Cezevi',
        "tabu1": 'Hapishane',
        "tabu2": 'Suçlu',
        "tabu3": 'Mahkum',
        "tabu4": 'Slivri',
        "tabu5": 'C tipi',
      },
      {
        "id": 102,
        "word": 'Kumanda',
        "tabu1": 'Tuş',
        "tabu2": 'Televizyon',
        "tabu3": 'Kızılötesi',
        "tabu4": 'Alıcı',
        "tabu5": 'Kanal',
      },
      {
        "id": 103,
        "word": 'Makas',
        "tabu1": 'Kesmek',
        "tabu2": 'Kurdele',
        "tabu3": 'Bıçak',
        "tabu4": 'Keskin',
        "tabu5": 'Kağıt',
      },
      {
        "id": 104,
        "word": 'Çarpışan Araba',
        "tabu1": 'Lunapark',
        "tabu2": 'Otomobil',
        "tabu3": 'Kaza',
        "tabu4": 'Eğlenmek',
        "tabu5": 'Kullanmak',
      },
      {
        "id": 105,
        "word": 'El Arabası',
        "tabu1": 'Tutmak',
        "tabu2": 'Sürmek',
        "tabu3": 'Tekerlek',
        "tabu4": 'Taşımak',
        "tabu5": 'Kaldırmak',
      },
      {
        "id": 106,
        "word": 'Şampiyonlar Ligi',
        "tabu1": 'UEFA',
        "tabu2": 'Avrupa',
        "tabu3": 'Takım',
        "tabu4": 'Turnuva',
        "tabu5": 'Gurup',
      },
      {
        "id": 107,
        "word": 'Merdiven',
        "tabu1": 'Basamak',
        "tabu2": 'Çıkmak',
        "tabu3": 'Yüksek',
        "tabu4": 'Yukarı',
        "tabu5": 'Kat',
      },
      {
        "id": 108,
        "word": 'Felsefe',
        "tabu1": 'Düşünmek',
        "tabu2": 'Filozof',
        "tabu3": 'Yunanistan',
        "tabu4": 'Aristo',
        "tabu5": 'Sokrates',
      },
      {
        "id": 109,
        "word": 'Sedan',
        "tabu1": 'Otomobil',
        "tabu2": 'Araba',
        "tabu3": 'kasa',
        "tabu4": 'Tip',
        "tabu5": 'Arka',
      }
    ];
  }
}
